# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get output directory
      id: get-output-dir
      run: echo "::set-output name=output_dir::$(dotnet build --no-restore --output . | grep -oP '(?<=Output Path: ).*')"
    - name: Compress build artifacts
      run: |
        mkdir -p build_artifacts
        tar -czvf build_artifacts/build.tar.gz -C ${{ steps.get-output-dir.outputs.output_dir }} .
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build_artifacts/build.tar.gz
